@startuml
class Booking{
    -seat : Seat
    -seatList : List<Seat>
    -counter : int
    -rowCounter : int

    +getSeatList() : List<Seat>
    +allocateSeats(int input) : String
    +seatAvailable(Int input) : boolean
}

Booking -> Seat

class Seat{
    -rows : Enum
    -seatNumber : Enum

    +getRows() : Enum
    +getSeatNumber() : Enum
}

Enum Row{
    A,
    B,
    C
}

Seat -> Row

Enum SeatNumber{
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE
}

Seat -> SeatNumber

@enduml